# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/src/Lab1PCD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/src/Lab1PCD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/Lab1PCD/CMakeFiles /usr/src/Lab1PCD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/src/Lab1PCD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app1

# Build rule for target.
app1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app1
.PHONY : app1

# fast build rule for target.
app1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1.dir/build.make CMakeFiles/app1.dir/build
.PHONY : app1/fast

#=============================================================================
# Target rules for targets named app2

# Build rule for target.
app2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app2
.PHONY : app2

# fast build rule for target.
app2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/build
.PHONY : app2/fast

#=============================================================================
# Target rules for targets named app3

# Build rule for target.
app3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app3
.PHONY : app3

# fast build rule for target.
app3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app3.dir/build.make CMakeFiles/app3.dir/build
.PHONY : app3/fast

src/app1.o: src/app1.c.o
.PHONY : src/app1.o

# target to build an object file
src/app1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1.dir/build.make CMakeFiles/app1.dir/src/app1.c.o
.PHONY : src/app1.c.o

src/app1.i: src/app1.c.i
.PHONY : src/app1.i

# target to preprocess a source file
src/app1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1.dir/build.make CMakeFiles/app1.dir/src/app1.c.i
.PHONY : src/app1.c.i

src/app1.s: src/app1.c.s
.PHONY : src/app1.s

# target to generate assembly for a file
src/app1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app1.dir/build.make CMakeFiles/app1.dir/src/app1.c.s
.PHONY : src/app1.c.s

src/app2.o: src/app2.c.o
.PHONY : src/app2.o

# target to build an object file
src/app2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/src/app2.c.o
.PHONY : src/app2.c.o

src/app2.i: src/app2.c.i
.PHONY : src/app2.i

# target to preprocess a source file
src/app2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/src/app2.c.i
.PHONY : src/app2.c.i

src/app2.s: src/app2.c.s
.PHONY : src/app2.s

# target to generate assembly for a file
src/app2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app2.dir/build.make CMakeFiles/app2.dir/src/app2.c.s
.PHONY : src/app2.c.s

src/app3.o: src/app3.c.o
.PHONY : src/app3.o

# target to build an object file
src/app3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app3.dir/build.make CMakeFiles/app3.dir/src/app3.c.o
.PHONY : src/app3.c.o

src/app3.i: src/app3.c.i
.PHONY : src/app3.i

# target to preprocess a source file
src/app3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app3.dir/build.make CMakeFiles/app3.dir/src/app3.c.i
.PHONY : src/app3.c.i

src/app3.s: src/app3.c.s
.PHONY : src/app3.s

# target to generate assembly for a file
src/app3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app3.dir/build.make CMakeFiles/app3.dir/src/app3.c.s
.PHONY : src/app3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app1"
	@echo "... app2"
	@echo "... app3"
	@echo "... src/app1.o"
	@echo "... src/app1.i"
	@echo "... src/app1.s"
	@echo "... src/app2.o"
	@echo "... src/app2.i"
	@echo "... src/app2.s"
	@echo "... src/app3.o"
	@echo "... src/app3.i"
	@echo "... src/app3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

